lib/queue_classic_plus/update_metrics.rb
spec/update_metrics_spec.rb

Our alerting on that didn't make sense anymore. So, now, we basically have two metrics similar: `max_created_at` which reports the biggest lag to process jobs that were enqueued for immediate processing, and `jobs_delayed.lag` which reports biggest lag to process jobs that were enqueued for scheduling and that are now ready to be processed.
@smathieu @rainforestapp/devs

only report max_created_at for never scheduled jobs

---

lib/queue_classic_plus/tasks/work.rake

Raven ignores ActiveRecord::RecordNotFound exceptions by default, which
is problematic in background processes. This is pretty hacky, but the
best way I could think of of dealing with the issue.
@rainforestapp/devs

Fix issue with Raven exception handling

---

.travis.yml
Gemfile
lib/queue_classic_plus/tasks/work.rake

Fixes #19
Confirmed locally that this behaves as expected (it will finish the
current job and then shut down).
@rainforestapp/core @ukd1

Finish current job on SIGTERM

---

lib/queue_classic_plus/base.rb
lib/queue_classic_plus/inheritable_attr.rb
lib/queue_classic_plus/worker.rb
spec/sample_jobs.rb
spec/worker_spec.rb

We already reconnect when the PG connection is lost mid-job, but the job
would normally get re-enqueued on the failed_jobs queue which isn't
ideal. Jobs should almost always be retried if the connection is lost. I
added a `disable_retries!` escape hatch for the rare occasion that
they're not.
See rainforestapp/Rainforest#7995
@rainforestapp/core @ukd1

Force-retry jobs when connection is lost

---

lib/queue_classic_plus/worker.rb
spec/sample_jobs.rb
spec/worker_spec.rb

Fixes RF-9
@rainforestapp/core 
Please see the issue comments on why this solves the issue. This fix will:
- prevent worker to fail if connection reaped during processing a job
- ensure to execute `ROLLBACK`
- not hide original exception with PG::UnableToSend

RF-9 fix worker fails with PG::UnableToSend

---

lib/queue_classic_plus/worker.rb
spec/sample_jobs.rb
spec/worker_spec.rb

We were retrying on *all* PG errors, which includes things like
constraint violations and other stuff that isn't retriable.

RF-2803 Be more discriminate with PG error retries

---

lib/queue_classic_plus/inheritable_attr.rb

Solves:
```
/home/ubuntu/Rainforest/vendor/bundle/ruby/2.4.0/bundler/gems/queue_classic_plus-e4112e954132/lib/queue_classic_plus/inheritable_attr.rb:31: warning: constant ::Fixnum is deprecated
/home/ubuntu/Rainforest/vendor/bundle/ruby/2.4.0/bundler/gems/queue_classic_plus-e4112e954132/lib/queue_classic_plus/inheritable_attr.rb:31: warning: constant ::Fixnum is deprecated
/home/ubuntu/Rainforest/vendor/bundle/ruby/2.4.0/bundler/gems/queue_classic_plus-e4112e954132/lib/queue_classic_plus/inheritable_attr.rb:31: warning: constant ::Fixnum is deprecated
/home/ubuntu/Rainforest/vendor/bundle/ruby/2.4.0/bundler/gems/queue_classic_plus-e4112e954132/lib/queue_classic_plus/inheritable_attr.rb:31: warning: constant ::Fixnum is deprecated
```

Remove Fixnum / Bignum if running > 2.4

---

.travis.yml
Gemfile
lib/queue_classic_plus/new_relic.rb
queue_classic_plus.gemspec
spec/new_relic_spec.rb

See https://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/
and https://sikac.hu/how-to-use-module-prepend-to-override-class-method-in-ruby-4197c6159cd3

Rewrite NewRelic extension to use Module.prepend rather than the deprecated alias_method_chain

---

README.md
lib/queue_classic_plus/tasks/work.rake
lib/queue_classic_plus/version.rb

Do what we did for Sentry 3 (`Raven`) for Sentry 4 as well (`Sentry`)

[RF-21797] Unexclude exceptions for Sentry 4 users

---

lib/queue_classic_plus/base.rb
lib/queue_classic_plus/version.rb
queue_classic_plus.gemspec
spec/base_spec.rb

The specs are written the way they are because I couldn't get `ActiveJob::Arguments.serialize` and `.deserialize` to work with just ActiveJob loaded, and I felt like requiring all of Rails, just for this one test, was overkill.

Use ActiveJob's (de)serialization when Rails is defined

---

lib/queue_classic_plus/tasks/work.rake
lib/queue_classic_plus/version.rb

Sentry [switched to asynchronous event sending](https://github.com/getsentry/sentry-ruby/blob/0e268090667d226120b33955d7a535ceab8e696a/sentry-ruby/CHANGELOG.md#events-are-sent-asynchronously) in v4.1.0. This causes events to not be sent by QC (similar to the issue raised in https://github.com/getsentry/sentry-ruby/issues/1324).

[RF-21864] Continue sending events to Sentry synchronously after Sentry 4.1 update

---

.circleci/config.yml
.gitignore
lib/queue_classic_plus/datadog.rb
spec/datadog_spec.rb

* Update to support Ruby 3.2.0
* Support both major versions for Datadog's gem `ddtrace`: 0.x and 1.x. 
* Make use of the newer major version Datadog gem API. See [link](https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md#removed-datadogtracer): 
> Removed `Datadog.tracer`
Many of the functions accessed directly through Datadog.tracer have been moved to Datadog::Tracing instead.
**NOTE:** We may still have to test the alerts/metrics manually to see if they are being directed to the correct place with the new version. Any thoughts on how to test that or who can help me with it?

RF-26342 Support ruby 3.2.0

---

Gemfile
lib/queue_classic_plus/datadog.rb
spec/datadog_spec.rb

If a Datadog service name is configured, use that when tracing. If it is not, continue to use the default qc.job.
Uses the `dry-configurable` gem. https://dry-rb.org/gems/dry-configurable/1.0/
Once this is shipped, we can configure our apps to give QC jobs the desired service name like this:
```
QueueClassicDatadog.config.dd_service = "desired service name"
```
Would be nice to have a proper Datadog integration so we could do:
```
Datadog.configure do |config|
config.tracing.instrument :queue_classic_plus, service_name: "rainforest-qc"
```
but I'm not sure what's involved in that and the implementation I've gone for is probably the simplest.

[RF-29783] Add configuration for Datadog service name

---

README.md

Adds documentation for how to configure Datadog service name for feature added in https://github.com/rainforestapp/queue_classic_plus/releases/tag/v4.0.0.alpha12
Also clarified documentation for gem publishing process.

Update Datadog service name documentation in README

---

lib/queue_classic_plus/base.rb
lib/queue_classic_plus/version.rb
spec/base_spec.rb

https://github.com/rainforestapp/queue_classic_plus/pull/56 made `lock!` thread safe, but it fails if `enqueue` is called while already in a transaction, because it creates a nested one.
First check if there is already a transaction before creating one.

[RF-29953] Fix thread safe enqueueing

---

lib/queue_classic_plus/base.rb
lib/queue_classic_plus/version.rb

https://github.com/rainforestapp/queue_classic_plus/pull/56 added a semaphore for thread safety. It uses a digest created from the queue name as a key for `pg_advisory_xact_lock` so the semaphore works on a per queue basis.
However, the digest can sometimes go out of range of postgres `bigint`.
Adding a `modulo` on the digest to prevent this.
While this opens up the possibility of key clashes, it is extremely unlikely.
This bug showed up here: https://app.circleci.com/pipelines/github/rainforestapp/Rainforest/36696/workflows/8442de01-be71-4c6c-8918-1e41f13784ba/jobs/355430/tests
I've tested the fix against the main app and it works.

[RF-29953] Fix queue_name_digest going out of range

---

lib/queue_classic_plus.rb
lib/queue_classic_plus/base.rb
lib/queue_classic_plus/queue_classic/queue.rb
lib/queue_classic_plus/version.rb
spec/base_spec.rb

The last attempt to make `lock!` threadsafe (https://github.com/rainforestapp/queue_classic_plus/pull/56) caused some major performance issues, because the lock key was on the  queue name, which means everything that wanted to enqueue something had to wait its turn to get a lock. And since the lock was on the transaction level, each turn also took the length of its transaction.
One solution I considered was reducing the scope of the lock key to specifically the (`q_name`, `job_name`, `arguments`). This would reduce the amount of locking significantly and probably would work. But it still has complications with transactions, like whether or not the `enqueue` is called from within a parent transaction or not and many locks being requested on the same transaction.
So I settled on this …

[RF-29953] Add conditional constraint on lock jobs

---

lib/queue_classic_plus.rb
lib/queue_classic_plus/base.rb
lib/queue_classic_plus/queue_classic/queue.rb
lib/queue_classic_plus/version.rb
spec/base_spec.rb

Reverts the implementation to [4.0.0.alpha13](https://github.com/rainforestapp/queue_classic_plus/releases/tag/v4.0.0.alpha13) which is the last stable version.
Reverted one merge commit at a time to make sure everything reverted properly. Finally incremented the version number to `4.0.0.alpha18`.
Shipping this to ensure stability before adding features in https://github.com/rainforestapp/queue_classic_plus/pull/60.

[RF-30293] Revert to 4.0.0.alpha13

---

README.md
lib/queue_classic_plus/base.rb
lib/queue_classic_plus/version.rb
spec/base_spec.rb

* ~~Reverts to 4.0.0.alpha13 implementation. The `lock!` fixes were not working and this was the last stable version.~~
* Adds callbacks around `enqueue` and `perform` so we can modify behaviour from the calling app instead of making changes to QC.
Example of how these callbacks can be used: https://github.com/rainforestapp/Rainforest/pull/22392
The callbacks are implemented as wrappers around the original method which call class methods in the job before/after calling the original implementation.
Other approaches considered:
I tried this and it could work. However, `queue_classic_plus` uses a completely different implementation than `ActiveJob`. `ActiveJob::QueueAdapter` expects jobs to be instantiated and instance methods called for `perform`, `enqueue` etc. `queue_classic_plus` works …

[RF-30285] Add QC job callbacks

---

lib/queue_classic_plus/version.rb
lib/queue_classic_plus/worker.rb
spec/worker_spec.rb

This was broken by #42, but we didn't notice until a mailer job blew up recently (for RFers, see linked Jira ticket).

[RF-31082] Properly handle failed non-QC jobs

---

lib/queue_classic_plus/version.rb
lib/queue_classic_plus/worker.rb

The same CustomWorker instance is used to handle multiple failures, which leads to the wrong job classes being enqueued for retries when subsequent failures are for different job classes.

[RF-31082] Fix memoization of failed job class in CustomWorker
